/**
 * Production - Batches Service
 */

import { apiClient } from "@/lib/api/client";
import type {
  ProductionBatch,
  CreateProductionBatchPayload,
  UpdateProductionBatchPayload,
  ProductionBatchFilters,
  ProductionReport,
  PaginatedResponse,
} from "@/types/api";

class BatchesService {
  private readonly BASE_PATH = "/production/batches";

  /**
   * Get list of production batches with optional filters
   */
  async getBatches(
    filters?: ProductionBatchFilters
  ): Promise<PaginatedResponse<ProductionBatch>> {
    return apiClient.get<PaginatedResponse<ProductionBatch>>(
      `${this.BASE_PATH}/`,
      {
        params: filters,
      }
    );
  }

  /**
   * Get a single batch by ID
   */
  async getBatch(id: number): Promise<ProductionBatch> {
    return apiClient.get<ProductionBatch>(`${this.BASE_PATH}/${id}/`);
  }

  /**
   * Create a new production batch
   * Batch number is auto-generated by backend
   */
  async createBatch(
    data: CreateProductionBatchPayload
  ): Promise<ProductionBatch> {
    return apiClient.post<ProductionBatch>(`${this.BASE_PATH}/`, data);
  }

  /**
   * Update a batch
   */
  async updateBatch(
    id: number,
    data: UpdateProductionBatchPayload
  ): Promise<ProductionBatch> {
    return apiClient.patch<ProductionBatch>(`${this.BASE_PATH}/${id}/`, data);
  }

  /**
   * Delete a batch
   */
  async deleteBatch(id: number): Promise<void> {
    return apiClient.delete<void>(`${this.BASE_PATH}/${id}/`);
  }

  /**
   * Start a production batch
   */
  async startBatch(id: number): Promise<ProductionBatch> {
    return apiClient.post<ProductionBatch>(`${this.BASE_PATH}/${id}/start/`);
  }

  /**
   * Mark batch as completed with production details
   */
  async completeBatch(
    id: number,
    data: {
      actual_quantity: number;
      milk_used: number;
      wastage_quantity?: number;
      quality_check_passed?: boolean;
      quality_notes?: string;
    }
  ): Promise<ProductionBatch> {
    return apiClient.post<ProductionBatch>(
      `${this.BASE_PATH}/${id}/complete/`,
      data
    );
  }

  /**
   * Get production statistics
   */
  async getBatchStats(days: number = 30): Promise<any> {
    return apiClient.get<any>(`${this.BASE_PATH}/stats/`, {
      params: { days },
    });
  }

  /**
   * Get production report
   */
  async getProductionReport(
    startDate?: string,
    endDate?: string
  ): Promise<ProductionReport> {
    return apiClient.get<ProductionReport>(
      `${this.BASE_PATH}/production_report/`,
      {
        params: { start_date: startDate, end_date: endDate },
      }
    );
  }
}

// Export singleton instance
export const batchesService = new BatchesService();
export default batchesService;
