# Generated by Django 4.2.25 on 2025-10-21 19:05

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique product identifier",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Product name", max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("dairy", "Dairy Products"),
                            ("sweets", "Sweets"),
                            ("beverages", "Beverages"),
                        ],
                        db_index=True,
                        help_text="Product category",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed product description"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "Kilogram"),
                            ("liter", "Liter"),
                            ("piece", "Piece"),
                            ("pack", "Pack"),
                        ],
                        help_text="Unit of measurement",
                        max_length=20,
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Cost price per unit", max_digits=10
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Selling price per unit",
                        max_digits=10,
                    ),
                ),
                (
                    "shelf_life_days",
                    models.IntegerField(help_text="Shelf life in days"),
                ),
                (
                    "storage_temperature",
                    models.CharField(
                        blank=True,
                        help_text="Required storage temperature",
                        max_length=50,
                    ),
                ),
                (
                    "milk_required_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Milk required per unit (in liters)",
                        max_digits=8,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether product is currently active"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Product image",
                        null=True,
                        upload_to="products/",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "products",
                "ordering": ["product_id"],
            },
        ),
        migrations.CreateModel(
            name="ProductionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique batch identifier",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("batch_date", models.DateField(help_text="Date of production batch")),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, help_text="Production start time", null=True
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, help_text="Production end time", null=True
                    ),
                ),
                (
                    "planned_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Planned production quantity",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "actual_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Actual production quantity",
                        max_digits=10,
                    ),
                ),
                (
                    "wastage_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Wastage quantity",
                        max_digits=10,
                    ),
                ),
                (
                    "milk_allocated",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Milk allocated for this batch (liters)",
                        max_digits=10,
                    ),
                ),
                (
                    "milk_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Actual milk used (liters)",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        help_text="Current batch status",
                        max_length=20,
                    ),
                ),
                (
                    "quality_check_passed",
                    models.BooleanField(
                        default=True, help_text="Whether quality check passed"
                    ),
                ),
                (
                    "quality_notes",
                    models.TextField(blank=True, help_text="Quality check notes"),
                ),
                (
                    "yield_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Yield percentage (actual/planned * 100)",
                        max_digits=5,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "recipe_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Recipe and ingredient details",
                    ),
                ),
                (
                    "operators",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Production operators",
                        related_name="operated_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product being manufactured",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="production.product",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Production supervisor",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Batch",
                "verbose_name_plural": "Production Batches",
                "db_table": "production_batches",
                "ordering": ["-batch_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductionSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "schedule_date",
                    models.DateField(help_text="Scheduled production date"),
                ),
                (
                    "planned_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Planned production quantity",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=1, help_text="Production priority (1=highest)"
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Schedule notes")),
                (
                    "batch",
                    models.OneToOneField(
                        blank=True,
                        help_text="Linked production batch",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule",
                        to="production.productionbatch",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product to be manufactured",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="production.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Schedule",
                "verbose_name_plural": "Production Schedules",
                "db_table": "production_schedules",
                "ordering": ["schedule_date", "priority"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["product_id"], name="products_product_c3fbc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["category"], name="products_categor_fce6e6_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="productionschedule",
            unique_together={("schedule_date", "product")},
        ),
        migrations.AddIndex(
            model_name="productionbatch",
            index=models.Index(
                fields=["batch_id"], name="production__batch_i_080209_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionbatch",
            index=models.Index(
                fields=["product", "batch_date"], name="production__product_2f997b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionbatch",
            index=models.Index(fields=["status"], name="production__status_6ca6f2_idx"),
        ),
    ]
