# Generated by Django 4.2.25 on 2025-10-21 18:26

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='updated at')),
                ('supplier_id', models.CharField(db_index=True, help_text='Unique identifier for the supplier', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Supplier name', max_length=200)),
                ('supplier_type', models.CharField(choices=[('farmer', 'Farmer'), ('cooperative', 'Cooperative')], help_text='Type of supplier', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], db_index=True, default='active', help_text='Current status of the supplier', max_length=20)),
                ('phone', models.CharField(help_text='Primary phone number', max_length=15)),
                ('alternate_phone', models.CharField(blank=True, help_text='Alternate phone number', max_length=15)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254)),
                ('address', models.TextField(help_text='Full address')),
                ('route_name', models.CharField(db_index=True, help_text='Collection route name', max_length=100)),
                ('collection_time', models.TimeField(help_text='Usual collection time')),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('account_holder_name', models.CharField(blank=True, max_length=200)),
                ('payment_cycle', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly')], default='monthly', help_text='Payment frequency', max_length=20)),
                ('avg_quality_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average quality score across all collections', max_digits=4)),
                ('total_milk_supplied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total liters of milk supplied', max_digits=12)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid to supplier', max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount pending to be paid', max_digits=12)),
                ('documents', models.JSONField(blank=True, default=dict, help_text='Document references and metadata')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'suppliers',
                'ordering': ['supplier_id'],
                'indexes': [models.Index(fields=['supplier_id'], name='suppliers_supplie_f88093_idx'), models.Index(fields=['route_name'], name='suppliers_route_n_30db00_idx'), models.Index(fields=['status'], name='suppliers_status_e3c425_idx')],
            },
        ),
        migrations.CreateModel(
            name='MilkCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='updated at')),
                ('collection_id', models.CharField(db_index=True, help_text='Unique collection identifier (auto-generated)', max_length=30, unique=True)),
                ('collection_date', models.DateField(db_index=True, help_text='Date of collection')),
                ('collection_time', models.TimeField(help_text='Time of collection')),
                ('milk_type', models.CharField(choices=[('cow', 'Cow Milk'), ('buffalo', 'Buffalo Milk'), ('mixed', 'Mixed Milk')], help_text='Type of milk', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity in liters', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fat_percentage', models.DecimalField(decimal_places=2, help_text='Fat content percentage', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('snf_percentage', models.DecimalField(decimal_places=2, help_text='SNF (Solids Not Fat) percentage', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('temperature', models.DecimalField(decimal_places=1, help_text='Milk temperature in Celsius', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))])),
                ('quality_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated quality score (0-100)', max_digits=4)),
                ('quality_status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('conditional', 'Conditional')], default='accepted', help_text='Quality assessment status', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable')),
                ('rate_per_liter', models.DecimalField(decimal_places=2, help_text='Rate per liter in currency', max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount for this collection', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('bmc_integration_data', models.JSONField(blank=True, default=dict, help_text='Data from BMC (Bulk Milk Cooler) integration')),
                ('collected_by', models.ForeignKey(blank=True, help_text='Staff member who collected the milk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_collections', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(help_text='Supplier providing the milk', on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='milk_management.supplier')),
            ],
            options={
                'verbose_name': 'Milk Collection',
                'verbose_name_plural': 'Milk Collections',
                'db_table': 'milk_collections',
                'ordering': ['-collection_date', '-collection_time'],
            },
        ),
        migrations.CreateModel(
            name='MilkPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='updated at')),
                ('payment_id', models.CharField(db_index=True, help_text='Unique payment identifier (auto-generated)', max_length=30, unique=True)),
                ('payment_date', models.DateField(db_index=True, help_text='Date of payment')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('cheque', 'Cheque')], help_text='Method of payment', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Payment status', max_length=20)),
                ('period_start', models.DateField(help_text='Start date of payment period')),
                ('period_end', models.DateField(help_text='End date of payment period')),
                ('transaction_reference', models.CharField(blank=True, help_text='General transaction reference', max_length=100)),
                ('upi_transaction_id', models.CharField(blank=True, help_text='UPI transaction ID if applicable', max_length=100)),
                ('cheque_number', models.CharField(blank=True, help_text='Cheque number if applicable', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('collections', models.ManyToManyField(blank=True, help_text='Collections covered by this payment', related_name='payments', to='milk_management.milkcollection')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Staff member who processed the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(help_text='Supplier receiving the payment', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='milk_management.supplier')),
            ],
            options={
                'verbose_name': 'Milk Payment',
                'verbose_name_plural': 'Milk Payments',
                'db_table': 'milk_payments',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['payment_id'], name='milk_paymen_payment_4da712_idx'), models.Index(fields=['supplier', 'payment_date'], name='milk_paymen_supplie_653b93_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='milkcollection',
            index=models.Index(fields=['collection_id'], name='milk_collec_collect_003d77_idx'),
        ),
        migrations.AddIndex(
            model_name='milkcollection',
            index=models.Index(fields=['supplier', 'collection_date'], name='milk_collec_supplie_d2d14a_idx'),
        ),
        migrations.AddIndex(
            model_name='milkcollection',
            index=models.Index(fields=['collection_date'], name='milk_collec_collect_b90413_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='milkcollection',
            unique_together={('supplier', 'collection_date', 'collection_time')},
        ),
    ]
