# Generated by Django 4.2.25 on 2025-10-21 18:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkcollection',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount for this collection', max_digits=10),
        ),
    ]
