# Generated by Django 4.2.25 on 2025-10-21 18:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milk_management", "0002_alter_milkcollection_total_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milkcollection",
            name="quality_score",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Calculated quality score (0-100)",
                max_digits=5,
            ),
        ),
    ]
