# Generated by Django 4.2.25 on 2026-02-06 13:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_management', '0005_rename_temperature_to_clr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkcollection',
            name='rate_per_snf',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rate per kg of SNF', max_digits=8),
        ),
    ]
