# Generated by Django 4.2.25 on 2026-02-07 10:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_management', '0006_alter_milkcollection_rate_per_snf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkcollection',
            name='rate_per_fat',
            field=models.DecimalField(decimal_places=2, help_text='Fat rate - price per kg of fat content (₹)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='milkcollection',
            name='rate_per_snf',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='SNF rate - price per kg of SNF content (₹)', max_digits=8),
        ),
    ]
