# Generated by Django 4.2.25 on 2026-02-08 00:00

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("milk_management", "0007_update_rate_field_help_text"),
        ("production", "0003_add_product_quality_to_productionbatch"),
        ("authentication", "0002_alter_refreshtoken_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="MilkSegregationPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plan_date", models.DateField(db_index=True, help_text="Segregation plan date")),
                (
                    "total_liters",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total liters available for segregation",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Optional notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the segregation plan",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="milk_segregation_plans",
                        to="authentication.user",
                    ),
                ),
            ],
            options={
                "db_table": "milk_segregation_plans",
                "ordering": ["-plan_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MilkSegregationItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocated_liters",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Milk allocated to this product (liters)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "planned_units",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Planned units based on milk requirement",
                        max_digits=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Optional item notes")),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="Segregation plan",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="milk_management.milksegregationplan",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product receiving allocation",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="milk_segregation_items",
                        to="production.product",
                    ),
                ),
            ],
            options={
                "db_table": "milk_segregation_items",
                "ordering": ["product__name"],
                "unique_together": {("plan", "product")},
            },
        ),
        migrations.AddIndex(
            model_name="milksegregationplan",
            index=models.Index(fields=["plan_date"], name="milk_segre_plan_da_8e92fb_idx"),
        ),
        migrations.AddIndex(
            model_name="milksegregationplan",
            index=models.Index(fields=["created_by"], name="milk_segre_created_1d9f8a_idx"),
        ),
        migrations.AddIndex(
            model_name="milksegregationitem",
            index=models.Index(fields=["plan", "product"], name="milk_segre_plan_pr_3f2c4c_idx"),
        ),
    ]
