# Generated by Django 4.2.25 on 2026-02-16 19:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_management', '0008_milk_segregation_plans'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='milksegregationitem',
            new_name='milk_segreg_plan_id_4e43f6_idx',
            old_name='milk_segre_plan_pr_3f2c4c_idx',
        ),
        migrations.RenameIndex(
            model_name='milksegregationplan',
            new_name='milk_segreg_plan_da_f50437_idx',
            old_name='milk_segre_plan_da_8e92fb_idx',
        ),
        migrations.RenameIndex(
            model_name='milksegregationplan',
            new_name='milk_segreg_created_ea4052_idx',
            old_name='milk_segre_created_1d9f8a_idx',
        ),
        migrations.AlterField(
            model_name='milkcollection',
            name='snf',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='SNF - Solids Not Fat (kg per liter)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('15.00'))]),
        ),
        migrations.AlterField(
            model_name='milksegregationitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='milksegregationitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='milksegregationplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='milksegregationplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('milk_supplier', 'Milk Supplier'), ('equipment', 'Equipment'), ('packaging', 'Packaging'), ('chemical', 'Chemical'), ('other', 'Other')], help_text='Type of supplier', max_length=20),
        ),
    ]
