/**
 * Inventory - Transactions Service
 */

import { apiClient } from "@/lib/api/client";
import type {
  StockTransaction,
  CreateStockTransactionPayload,
  StockTransactionFilters,
  TransactionStats,
  PaginatedResponse,
} from "@/types/api";

class TransactionsService {
  private readonly BASE_PATH = "/inventory/transactions";

  /**
   * Get list of stock transactions with optional filters
   */
  async getTransactions(
    filters?: StockTransactionFilters
  ): Promise<PaginatedResponse<StockTransaction>> {
    return apiClient.get<PaginatedResponse<StockTransaction>>(
      `${this.BASE_PATH}/`,
      {
        params: filters,
      }
    );
  }

  /**
   * Get a single transaction by ID
   */
  async getTransaction(id: number): Promise<StockTransaction> {
    return apiClient.get<StockTransaction>(`${this.BASE_PATH}/${id}/`);
  }

  /**
   * Create a new stock transaction
   * Transaction ID is auto-generated by backend
   */
  async createTransaction(
    data: CreateStockTransactionPayload
  ): Promise<StockTransaction> {
    return apiClient.post<StockTransaction>(`${this.BASE_PATH}/`, data);
  }

  /**
   * Get transaction statistics
   * Supports date range filtering
   */
  async getTransactionStats(params?: {
    start_date?: string;
    end_date?: string;
  }): Promise<TransactionStats> {
    return apiClient.get<TransactionStats>(`${this.BASE_PATH}/stats/`, {
      params,
    });
  }
}

// Export singleton instance
export const transactionsService = new TransactionsService();
export default transactionsService;
