# Generated by Django 4.2.25 on 2025-10-21 20:15

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "department_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique department identifier",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Department name", max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Department description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether department is active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique employee identifier",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="First name", max_length=100),
                ),
                ("last_name", models.CharField(help_text="Last name", max_length=100)),
                ("date_of_birth", models.DateField(help_text="Date of birth")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        help_text="Gender",
                        max_length=10,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                        ],
                        help_text="Marital status",
                        max_length=20,
                    ),
                ),
                (
                    "personal_email",
                    models.EmailField(
                        blank=True, help_text="Personal email address", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(help_text="Primary phone number", max_length=15),
                ),
                (
                    "alternate_phone",
                    models.CharField(
                        blank=True, help_text="Alternate phone number", max_length=15
                    ),
                ),
                ("current_address", models.TextField(help_text="Current address")),
                (
                    "permanent_address",
                    models.TextField(blank=True, help_text="Permanent address"),
                ),
                ("city", models.CharField(help_text="City", max_length=100)),
                ("state", models.CharField(help_text="State", max_length=100)),
                ("pincode", models.CharField(help_text="Pincode", max_length=10)),
                (
                    "emergency_contact_name",
                    models.CharField(
                        help_text="Emergency contact name", max_length=200
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        help_text="Emergency contact phone", max_length=15
                    ),
                ),
                (
                    "emergency_contact_relation",
                    models.CharField(
                        help_text="Emergency contact relation", max_length=50
                    ),
                ),
                ("date_of_joining", models.DateField(help_text="Date of joining")),
                (
                    "date_of_leaving",
                    models.DateField(
                        blank=True, help_text="Date of leaving", null=True
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("temporary", "Temporary"),
                        ],
                        help_text="Employment type",
                        max_length=20,
                    ),
                ),
                (
                    "probation_period_months",
                    models.IntegerField(
                        default=6, help_text="Probation period in months"
                    ),
                ),
                (
                    "is_probation_completed",
                    models.BooleanField(
                        default=False, help_text="Whether probation is completed"
                    ),
                ),
                (
                    "designation",
                    models.CharField(help_text="Designation", max_length=100),
                ),
                (
                    "aadhaar_number",
                    models.CharField(
                        blank=True, help_text="Aadhaar number", max_length=12
                    ),
                ),
                (
                    "pan_number",
                    models.CharField(blank=True, help_text="PAN number", max_length=10),
                ),
                (
                    "documents",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Employee documents metadata",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(blank=True, help_text="Bank name", max_length=100),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True, help_text="Bank account number", max_length=50
                    ),
                ),
                (
                    "ifsc_code",
                    models.CharField(blank=True, help_text="IFSC code", max_length=20),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether employee is active"
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Department",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="employees.department",
                    ),
                ),
                (
                    "reporting_manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reporting manager",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_members",
                        to="employees.employee",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "db_table": "employees",
                "ordering": ["employee_id"],
            },
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Leave type name", max_length=100, unique=True
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Leave type code", max_length=20, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Leave type description"),
                ),
                (
                    "days_per_year",
                    models.IntegerField(help_text="Number of days allocated per year"),
                ),
                (
                    "is_paid",
                    models.BooleanField(
                        default=True, help_text="Whether leave is paid"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether leave type is active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Type",
                "verbose_name_plural": "Leave Types",
                "db_table": "leave_types",
            },
        ),
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "basic_salary",
                    models.DecimalField(
                        decimal_places=2, help_text="Basic salary", max_digits=10
                    ),
                ),
                (
                    "hra",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="House Rent Allowance",
                        max_digits=10,
                    ),
                ),
                (
                    "da",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Dearness Allowance",
                        max_digits=10,
                    ),
                ),
                (
                    "transport_allowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Transport allowance",
                        max_digits=10,
                    ),
                ),
                (
                    "medical_allowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Medical allowance",
                        max_digits=10,
                    ),
                ),
                (
                    "special_allowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Special allowance",
                        max_digits=10,
                    ),
                ),
                (
                    "provident_fund",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Provident fund deduction",
                        max_digits=10,
                    ),
                ),
                (
                    "professional_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Professional tax",
                        max_digits=10,
                    ),
                ),
                (
                    "income_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Income tax",
                        max_digits=10,
                    ),
                ),
                (
                    "gross_salary",
                    models.DecimalField(
                        decimal_places=2, help_text="Gross salary", max_digits=10
                    ),
                ),
                (
                    "total_deductions",
                    models.DecimalField(
                        decimal_places=2, help_text="Total deductions", max_digits=10
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        decimal_places=2, help_text="Net salary", max_digits=10
                    ),
                ),
                ("effective_from", models.DateField(help_text="Effective from date")),
                (
                    "effective_to",
                    models.DateField(
                        blank=True, help_text="Effective to date", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether salary structure is active"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_structures",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salary Structure",
                "verbose_name_plural": "Salary Structures",
                "db_table": "salary_structures",
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "review_period_start",
                    models.DateField(help_text="Review period start date"),
                ),
                (
                    "review_period_end",
                    models.DateField(help_text="Review period end date"),
                ),
                ("review_date", models.DateField(help_text="Review conducted date")),
                (
                    "quality_of_work",
                    models.IntegerField(
                        help_text="Quality of work rating",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "productivity",
                    models.IntegerField(
                        help_text="Productivity rating",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "communication",
                    models.IntegerField(
                        help_text="Communication rating",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "teamwork",
                    models.IntegerField(
                        help_text="Teamwork rating",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "initiative",
                    models.IntegerField(
                        help_text="Initiative rating",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "overall_rating",
                    models.DecimalField(
                        decimal_places=2, help_text="Overall rating", max_digits=3
                    ),
                ),
                ("strengths", models.TextField(help_text="Employee strengths")),
                (
                    "areas_of_improvement",
                    models.TextField(help_text="Areas needing improvement"),
                ),
                (
                    "goals_for_next_period",
                    models.TextField(help_text="Goals for next review period"),
                ),
                (
                    "reviewer_comments",
                    models.TextField(blank=True, help_text="Reviewer comments"),
                ),
                (
                    "employee_comments",
                    models.TextField(blank=True, help_text="Employee comments"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee being reviewed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reviews",
                        to="employees.employee",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reviewer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Review",
                "verbose_name_plural": "Performance Reviews",
                "db_table": "performance_reviews",
                "ordering": ["-review_date"],
            },
        ),
        migrations.AddField(
            model_name="department",
            name="head",
            field=models.ForeignKey(
                blank=True,
                help_text="Department head",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="department_head_of",
                to="employees.employee",
            ),
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                ("date", models.DateField(help_text="Attendance date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("half_day", "Half Day"),
                            ("on_leave", "On Leave"),
                            ("wfh", "Work From Home"),
                            ("holiday", "Holiday"),
                        ],
                        help_text="Attendance status",
                        max_length=20,
                    ),
                ),
                (
                    "check_in_time",
                    models.TimeField(blank=True, help_text="Check-in time", null=True),
                ),
                (
                    "check_out_time",
                    models.TimeField(blank=True, help_text="Check-out time", null=True),
                ),
                (
                    "working_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total working hours",
                        max_digits=4,
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Overtime hours",
                        max_digits=4,
                    ),
                ),
                (
                    "check_in_location",
                    models.CharField(
                        blank=True, help_text="Check-in location", max_length=200
                    ),
                ),
                (
                    "check_out_location",
                    models.CharField(
                        blank=True, help_text="Check-out location", max_length=200
                    ),
                ),
                (
                    "reason_for_absence",
                    models.TextField(blank=True, help_text="Reason for absence"),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Approved by user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="employees.employee",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Marked by user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendance Records",
                "db_table": "attendance",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PayrollRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        help_text="Month",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                ("year", models.IntegerField(help_text="Year")),
                (
                    "working_days",
                    models.IntegerField(help_text="Total working days in month"),
                ),
                ("days_present", models.IntegerField(help_text="Days present")),
                (
                    "days_absent",
                    models.IntegerField(default=0, help_text="Days absent"),
                ),
                (
                    "days_on_leave",
                    models.IntegerField(default=0, help_text="Days on leave"),
                ),
                (
                    "gross_salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Gross salary for the month",
                        max_digits=10,
                    ),
                ),
                (
                    "deductions",
                    models.DecimalField(
                        decimal_places=2, help_text="Total deductions", max_digits=10
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        decimal_places=2, help_text="Net salary", max_digits=10
                    ),
                ),
                (
                    "bonus",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Bonus amount",
                        max_digits=10,
                    ),
                ),
                (
                    "incentive",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Incentive amount",
                        max_digits=10,
                    ),
                ),
                (
                    "overtime_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Overtime payment",
                        max_digits=10,
                    ),
                ),
                (
                    "total_payable",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total payable amount",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                        ],
                        default="draft",
                        help_text="Payroll status",
                        max_length=20,
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(blank=True, help_text="Payment date", null=True),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, help_text="Payment method", max_length=50
                    ),
                ),
                (
                    "transaction_reference",
                    models.CharField(
                        blank=True, help_text="Transaction reference", max_length=100
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Approved by user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payrolls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_records",
                        to="employees.employee",
                    ),
                ),
                (
                    "salary_structure",
                    models.ForeignKey(
                        help_text="Salary structure",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employees.salarystructure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Record",
                "verbose_name_plural": "Payroll Records",
                "db_table": "payroll_records",
                "ordering": ["-year", "-month"],
                "unique_together": {("employee", "month", "year")},
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                ("from_date", models.DateField(help_text="Leave start date")),
                ("to_date", models.DateField(help_text="Leave end date")),
                (
                    "number_of_days",
                    models.DecimalField(
                        decimal_places=2, help_text="Number of leave days", max_digits=5
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for leave")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Leave request status",
                        max_length=20,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, help_text="Approval timestamp", null=True
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, help_text="Reason for rejection"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Approved by user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="employees.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        help_text="Leave type",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employees.leavetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Request",
                "verbose_name_plural": "Leave Requests",
                "db_table": "leave_requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "from_date"],
                        name="leave_reque_employe_05abf2_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(help_text="Year")),
                (
                    "allocated",
                    models.DecimalField(
                        decimal_places=2, help_text="Allocated leave days", max_digits=5
                    ),
                ),
                (
                    "used",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Used leave days",
                        max_digits=5,
                    ),
                ),
                (
                    "available",
                    models.DecimalField(
                        decimal_places=2, help_text="Available leave days", max_digits=5
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="employees.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        help_text="Leave type",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.leavetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Balance",
                "verbose_name_plural": "Leave Balances",
                "db_table": "leave_balances",
                "unique_together": {("employee", "leave_type", "year")},
            },
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["employee_id"], name="employees_employe_0b5eb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["department"], name="employees_departm_24ab5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["employee", "date"], name="attendance_employe_c9bb2b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("employee", "date")},
        ),
    ]
