/**
 * Milk Management - Collections Service
 */

import { apiClient } from "@/lib/api/client";
import type {
  MilkCollection,
  CreateMilkCollectionPayload,
  UpdateMilkCollectionPayload,
  MilkCollectionFilters,
  CollectionStats,
  CollectionsBySupplier,
  TodayCollections,
  PaginatedResponse,
} from "@/types/api";

class CollectionsService {
  private readonly BASE_PATH = "/milk/collections";

  /**
   * Get list of collections with optional filters
   */
  async getCollections(
    filters?: MilkCollectionFilters
  ): Promise<PaginatedResponse<MilkCollection>> {
    return apiClient.get<PaginatedResponse<MilkCollection>>(
      `${this.BASE_PATH}/`,
      {
        params: filters,
      }
    );
  }

  /**
   * Get a single collection by ID
   */
  async getCollection(id: number): Promise<MilkCollection> {
    return apiClient.get<MilkCollection>(`${this.BASE_PATH}/${id}/`);
  }

  /**
   * Create a new milk collection
   * Collection ID is auto-generated by backend
   */
  async createCollection(
    data: CreateMilkCollectionPayload
  ): Promise<MilkCollection> {
    return apiClient.post<MilkCollection>(`${this.BASE_PATH}/`, data);
  }

  /**
   * Update a collection
   */
  async updateCollection(
    id: number,
    data: UpdateMilkCollectionPayload
  ): Promise<MilkCollection> {
    return apiClient.patch<MilkCollection>(`${this.BASE_PATH}/${id}/`, data);
  }

  /**
   * Delete a collection
   */
  async deleteCollection(id: number): Promise<void> {
    return apiClient.delete<void>(`${this.BASE_PATH}/${id}/`);
  }

  /**
   * Get collection statistics
   */
  async getCollectionStats(days: number = 7): Promise<CollectionStats> {
    return apiClient.get<CollectionStats>(`${this.BASE_PATH}/stats/`, {
      params: { days },
    });
  }

  /**
   * Get collections grouped by supplier
   */
  async getCollectionsBySupplier(
    days: number = 7
  ): Promise<CollectionsBySupplier[]> {
    return apiClient.get<CollectionsBySupplier[]>(
      `${this.BASE_PATH}/by_supplier/`,
      {
        params: { days },
      }
    );
  }

  /**
   * Get today's collections
   */
  async getTodayCollections(): Promise<TodayCollections> {
    return apiClient.get<TodayCollections>(`${this.BASE_PATH}/today/`);
  }
}

// Export singleton instance
export const collectionsService = new CollectionsService();
export default collectionsService;
