/**
 * Milk Management - Payments Service
 */

import { apiClient } from "@/lib/api/client";
import type {
  Payment,
  CreatePaymentPayload,
  UpdatePaymentPayload,
  PaymentFilters,
  PaymentStats,
  PendingPayment,
  PaginatedResponse,
  ActionResponse,
} from "@/types/api";

class PaymentsService {
  private readonly BASE_PATH = "/milk/payments";

  /**
   * Get list of payments with optional filters
   */
  async getPayments(
    filters?: PaymentFilters
  ): Promise<PaginatedResponse<Payment>> {
    return apiClient.get<PaginatedResponse<Payment>>(`${this.BASE_PATH}/`, {
      params: filters,
    });
  }

  /**
   * Get a single payment by ID
   */
  async getPayment(id: number): Promise<Payment> {
    return apiClient.get<Payment>(`${this.BASE_PATH}/${id}/`);
  }

  /**
   * Create a new payment
   * Payment ID is auto-generated by backend
   */
  async createPayment(data: CreatePaymentPayload): Promise<Payment> {
    return apiClient.post<Payment>(`${this.BASE_PATH}/`, data);
  }

  /**
   * Update a payment
   */
  async updatePayment(
    id: number,
    data: UpdatePaymentPayload
  ): Promise<Payment> {
    return apiClient.patch<Payment>(`${this.BASE_PATH}/${id}/`, data);
  }

  /**
   * Delete a payment
   */
  async deletePayment(id: number): Promise<void> {
    return apiClient.delete<void>(`${this.BASE_PATH}/${id}/`);
  }

  /**
   * Get pending payments
   */
  async getPendingPayments(): Promise<PendingPayment[]> {
    return apiClient.get<PendingPayment[]>(`${this.BASE_PATH}/pending/`);
  }

  /**
   * Mark payment as completed
   */
  async markCompleted(
    id: number,
    transactionReference?: string
  ): Promise<Payment> {
    return apiClient.post<Payment>(`${this.BASE_PATH}/${id}/mark_completed/`, {
      transaction_reference: transactionReference,
    });
  }

  /**
   * Mark payment as failed
   */
  async markFailed(id: number, reason?: string): Promise<Payment> {
    return apiClient.post<Payment>(`${this.BASE_PATH}/${id}/mark_failed/`, {
      reason,
    });
  }

  /**
   * Get payment statistics
   */
  async getPaymentStats(days: number = 30): Promise<PaymentStats> {
    return apiClient.get<PaymentStats>(`${this.BASE_PATH}/stats/`, {
      params: { days },
    });
  }
}

// Export singleton instance
export const paymentsService = new PaymentsService();
export default paymentsService;
