# Generated by Django 4.2.25 on 2025-10-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="inventoryitem",
            new_name="inventory_i_item_id_168234_idx",
            old_name="inventory_i_item_id_b8e9e7_idx",
        ),
        migrations.RenameIndex(
            model_name="inventoryitem",
            new_name="inventory_i_item_ty_2421a1_idx",
            old_name="inventory_i_item_ty_8f3c9a_idx",
        ),
        migrations.RenameIndex(
            model_name="stocktransaction",
            new_name="stock_trans_transac_4fdecc_idx",
            old_name="stock_trans_transac_f8a9c1_idx",
        ),
        migrations.RenameIndex(
            model_name="stocktransaction",
            new_name="stock_trans_item_id_c90b89_idx",
            old_name="stock_trans_item_id_4e7f2b_idx",
        ),
        migrations.RenameIndex(
            model_name="stocktransaction",
            new_name="stock_trans_transac_b2b788_idx",
            old_name="stock_trans_transac_9d2e5c_idx",
        ),
        migrations.AlterField(
            model_name="finishedgoodsstock",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this record was created",
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="finishedgoodsstock",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when this record was last updated",
                verbose_name="updated at",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this record was created",
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when this record was last updated",
                verbose_name="updated at",
            ),
        ),
        migrations.AlterField(
            model_name="rawmaterialstock",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this record was created",
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="rawmaterialstock",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when this record was last updated",
                verbose_name="updated at",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this record was created",
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when this record was last updated",
                verbose_name="updated at",
            ),
        ),
    ]
