# Generated by Django 4.2.25 on 2025-10-21 19:46

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "inventory",
            "0002_rename_inventory_i_item_id_b8e9e7_idx_inventory_i_item_id_168234_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodsReceiptNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "grn_number",
                    models.CharField(db_index=True, max_length=30, unique=True),
                ),
                ("receipt_date", models.DateField()),
                (
                    "quality_status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("partial", "Partial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quality_notes", models.TextField(blank=True)),
                (
                    "delivery_challan_number",
                    models.CharField(blank=True, max_length=50),
                ),
                ("invoice_number", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "goods_receipt_notes",
                "ordering": ["-receipt_date"],
            },
        ),
        migrations.CreateModel(
            name="GRNItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordered_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "received_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "accepted_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "rejected_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("quality_check_passed", models.BooleanField(default=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("batch_number", models.CharField(blank=True, max_length=50)),
                ("expiry_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "grn_items",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "po_number",
                    models.CharField(db_index=True, max_length=30, unique=True),
                ),
                ("po_date", models.DateField()),
                ("expected_delivery_date", models.DateField()),
                ("actual_delivery_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("sent", "Sent"),
                            ("confirmed", "Confirmed"),
                            ("partially_received", "Partially Received"),
                            ("fully_received", "Fully Received"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=25,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("delivery_address", models.TextField()),
                ("shipping_method", models.CharField(blank=True, max_length=100)),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                ("terms_and_conditions", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurrence_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "purchase_orders",
                "ordering": ["-po_date"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(max_length=20)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "quantity_received",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            options={
                "db_table": "purchase_order_items",
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "vendor_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("company_name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("raw_material", "Raw Material"),
                            ("packaging", "Packaging"),
                            ("equipment", "Equipment"),
                            ("service", "Service"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("contact_person", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=15)),
                ("alternate_phone", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("billing_address", models.TextField()),
                ("shipping_address", models.TextField(blank=True)),
                ("gst_number", models.CharField(blank=True, max_length=20)),
                ("pan_number", models.CharField(blank=True, max_length=20)),
                (
                    "company_registration_number",
                    models.CharField(blank=True, max_length=50),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("account_number", models.CharField(blank=True, max_length=50)),
                ("ifsc_code", models.CharField(blank=True, max_length=20)),
                ("account_holder_name", models.CharField(blank=True, max_length=200)),
                ("credit_period_days", models.IntegerField(default=30)),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("bank_transfer", "Bank Transfer"),
                            ("upi", "UPI"),
                        ],
                        default="bank_transfer",
                        max_length=20,
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_purchases",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_payments",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "outstanding_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("documents", models.JSONField(default=dict)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "vendors",
                "ordering": ["vendor_id"],
            },
        ),
        migrations.CreateModel(
            name="VendorPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(db_index=True, max_length=30, unique=True),
                ),
                ("payment_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("upi", "UPI"),
                            ("cheque", "Cheque"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_advance", models.BooleanField(default=False)),
                ("transaction_reference", models.CharField(blank=True, max_length=100)),
                ("upi_transaction_id", models.CharField(blank=True, max_length=100)),
                ("cheque_number", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase_orders",
                    models.ManyToManyField(
                        blank=True, related_name="payments", to="vendors.purchaseorder"
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "vendor_payments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(fields=["vendor_id"], name="vendors_vendor__d618c9_idx"),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(fields=["status"], name="vendors_status_079e23_idx"),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="po_items",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="vendors.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_pos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_pos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="vendors.vendor",
            ),
        ),
        migrations.AddField(
            model_name="grnitem",
            name="grn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="vendors.goodsreceiptnote",
            ),
        ),
        migrations.AddField(
            model_name="grnitem",
            name="po_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="vendors.purchaseorderitem",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grns",
                to="vendors.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="quality_checked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quality_checked_grns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_grns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="vendorpayment",
            index=models.Index(
                fields=["payment_id"], name="vendor_paym_payment_7aef8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorpayment",
            index=models.Index(
                fields=["vendor", "payment_date"], name="vendor_paym_vendor__b32e83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["po_number"], name="purchase_or_po_numb_656941_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["vendor", "po_date"], name="purchase_or_vendor__cc5ec8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(fields=["status"], name="purchase_or_status_5ac239_idx"),
        ),
        migrations.AddIndex(
            model_name="goodsreceiptnote",
            index=models.Index(
                fields=["grn_number"], name="goods_recei_grn_num_ee0ca1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goodsreceiptnote",
            index=models.Index(
                fields=["purchase_order"], name="goods_recei_purchas_213a98_idx"
            ),
        ),
    ]
