# Generated by Django 4.2.25 on 2025-12-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendorinvoice_vendorinvoiceitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='documents',
            field=models.JSONField(blank=True, default=dict, help_text='Optional. Leave empty or enter valid JSON (e.g., {} for empty, or {"license": "ABC123"})'),
        ),
    ]
