# Generated by Django 4.2.25 on 2026-01-01 16:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        ('vendors', '0003_improve_documents_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinvoiceitem',
            name='applied_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual price applied (vendor-specific or market)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorinvoiceitem',
            name='is_vendor_price',
            field=models.BooleanField(default=False, help_text='True if vendor-specific pricing was applied'),
        ),
        migrations.AddField(
            model_name='vendorinvoiceitem',
            name='market_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standard market price per unit', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorinvoiceitem',
            name='price_savings',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total savings vs market price', max_digits=12),
        ),
        migrations.CreateModel(
            name='VendorProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='updated at')),
                ('vendor_price', models.DecimalField(decimal_places=2, help_text='Special price for this vendor (per unit)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('min_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum order quantity to qualify for this price', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this pricing is currently active')),
                ('valid_from', models.DateField(blank=True, help_text='Start date for this pricing (optional)', null=True)),
                ('valid_until', models.DateField(blank=True, help_text='End date for this pricing (optional)', null=True)),
                ('notes', models.TextField(blank=True, help_text="Notes about this pricing arrangement (e.g., 'Bulk deal for Q1 2026')")),
                ('product', models.ForeignKey(help_text='Product with special pricing', on_delete=django.db.models.deletion.CASCADE, related_name='vendor_prices', to='production.product')),
                ('vendor', models.ForeignKey(help_text='Vendor receiving special pricing', on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Product Price',
                'verbose_name_plural': 'Vendor Product Prices',
                'db_table': 'vendor_product_prices',
                'ordering': ['vendor', 'product'],
                'indexes': [models.Index(fields=['vendor', 'is_active'], name='vendor_prod_vendor__b6ec13_idx'), models.Index(fields=['product', 'is_active'], name='vendor_prod_product_e02501_idx')],
                'unique_together': {('vendor', 'product')},
            },
        ),
    ]
