# Generated by Django 4.2.25 on 2026-02-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_add_grn_delivery_tracking'),
        ('vendors', '0004_add_vendor_product_pricing'),
    ]

    operations = [
    ]
