# Generated by Django 4.2.25 on 2026-02-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_add_vendorinvoice_purchase_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='category',
            field=models.CharField(choices=[('dairy_counter', 'Dairy Counter'), ('hotel', 'Hotel'), ('cafe', 'Cafe'), ('restaurant', 'Restaurant')], max_length=20),
        ),
    ]
